# Generated by Django 3.0.6 on 2020-07-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('my_admin', '0002_auto_20200629_1359'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'venda'},
        ),
        migrations.AlterModelOptions(
            name='checkoutitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
        migrations.AlterField(
            model_name='checkout',
            name='bank_slip_url',
            field=models.URLField(null=True, verbose_name='url do boleto'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='customer_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.CustomerAddress', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_admin.PaymentMethod', verbose_name='método de pagamento'),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentgateway_tenants', to='tenant.Tenant', verbose_name='tenant'),
        ),
    ]
