# Generated by Django 3.0.6 on 2020-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200702_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='remote_id',
            field=models.CharField(default=None, help_text='id remoto da fatura no gateway de pagamento', max_length=255, null=True, verbose_name='id remoto da fatura'),
        ),
    ]
