# Generated by Django 3.0.6 on 2020-06-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'fatura'},
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='checkout',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='my_admin.Checkout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='customer_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_admin.CustomerAddress', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='remote_plan_id',
            field=models.CharField(help_text='id remoto do plano no gateway de pagamento', max_length=255, verbose_name='id remoto do plano'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_date',
            field=models.DateField(verbose_name='fim'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='remote_subscription_id',
            field=models.CharField(help_text='id da assinatura no gateway de pagamento', max_length=255, verbose_name='id remoto da assinatura'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(verbose_name='início'),
        ),
    ]
